//action types
export const FETCH_GENERAL_DATA= 'FETCH_GENERAL_DATA'
export const FETCH_GENERAL_DATA_SUCCESS= 'FETCH_GENERAL_DATA_SUCCESS'
export const FETCH_TECHNICAL_DATA= 'TECHNICAL_GENERAL_DATA'
export const FETCH_TECHNICAL_DATA_SUCCESS= 'TECHNICAL_GENERAL_DATA_SUCCESS'
export const FETCH_SPORTS_DATA= 'SPORTS_GENERAL_DATA'
export const FETCH_SPORTS_DATA_SUCCESS= 'SPORTS_GENERAL_DATA_SUCCESS'

export const FETCHING_FAILED= 'FETCHING_FAILED'